### ISSUE TITLE
Conflicting Copyright, and Licence

### ISSUE THREAD

**Issue by joshualouden** [4ut0m4t0n/alacarte#2]
Your exclamation of copyright, and the license you have applied to this repo conflicts. If forked, it could be advisable as change, and be in violation with your copyright claim, yet inline with your license.  Please clarify.

**Comment by 4ut0m4t0n** [comment]
Thank you pointing out the conflict.  Removed the references to "copyright", which were unintentional artifacts.  Still new to this.

**Comment by joshualouden** [comment]
Thanks! Also, I like your script by the way!
